### ISSUE TITLE
Cannot find module 'node-static'

### ISSUE THREAD

**Issue by codeiain** [sedouard/resume#2]
Hi am trying to run your example but on my azure website I keep getting the error Cannot find module 'node-static'.

This is the error am getting

Error: Cannot find module 'node-static'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\home\site\repository\node_modules\resume-cli\lib\serve.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\home\site\repository\node_modules\resume-cli\lib\index.js:8:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
npm ERR! Test failed.  See above for more details.

**Comment by codeiain** [comment]
I managed to work this out,

I had to add     "node-static": "^0.7.6", the the package.json file
